2025-09-24 11:13:57.995 [info] Extension host with pid 796489 started
2025-09-24 11:13:58.391 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-09-24 11:13:58.436 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2025-09-24 11:13:58.460 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-09-24 11:13:58.606 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-09-24 11:13:59.210 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-09-24 11:13:59.224 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-09-24 11:13:59.340 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-09-24 11:13:59.547 [info] Eager extensions activated
2025-09-24 11:13:59.579 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-09-24 11:13:59.586 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-09-24 11:13:59.641 [info] ExtensionService#_doActivateExtension sainnhe.everforest, startup: false, activationEvent: 'onStartupFinished'
2025-09-24 11:20:05.633 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.debugpy
2025-09-24 11:20:06.422 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2025-09-24 11:20:07.176 [info] ExtensionService#_doActivateExtension vscode.terminal-suggest, startup: false, activationEvent: 'onTerminalShellIntegration:*'
2025-09-24 11:20:58.886 [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
2025-09-25 14:15:45.084 [error] [ms-python.python] provider FAILED
2025-09-25 14:15:45.109 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:15:45.543 [error] [ms-python.python] provider FAILED
2025-09-25 14:15:45.543 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:21:41.431 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onTerminalQuickFixRequest:ms-vscode.npm-command'
2025-09-25 14:32:38.119 [error] [ms-python.python] provider FAILED
2025-09-25 14:32:38.119 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:49:22.711 [error] [ms-python.python] provider FAILED
2025-09-25 14:49:22.712 [error] Error: KeyError: 'age'
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:49:23.679 [error] [ms-python.python] provider FAILED
2025-09-25 14:49:23.680 [error] Error: KeyError: "age'"
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:49:52.415 [error] [ms-python.python] provider FAILED
2025-09-25 14:49:52.415 [error] Error: KeyError: 'age'
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:49:58.047 [error] [ms-python.python] provider FAILED
2025-09-25 14:49:58.047 [error] Error: KeyError: 'age'
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:49:59.198 [error] [ms-python.python] provider FAILED
2025-09-25 14:49:59.198 [error] Error: KeyError: 'name'
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 14:50:01.256 [error] [ms-python.python] provider FAILED
2025-09-25 14:50:01.256 [error] Error: KeyError: "name'"
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 15:11:30.739 [error] [ms-python.python] provider FAILED
2025-09-25 15:11:30.739 [error] Error: ValueError: `column` parameter (3) is not in a valid range (0-0) for line 3 ('').
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 15:25:13.734 [error] [ms-python.python] provider FAILED
2025-09-25 15:25:13.735 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-25 15:51:33.430 [error] [ms-python.python] provider FAILED
2025-09-25 15:51:33.430 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/kuma/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
2025-09-26 17:07:47.537 [info] Extension host terminating: renderer closed the MessagePort
2025-09-26 17:07:47.589 [info] Extension host with pid 796489 exiting with code 0
